Problem 3: Mathematical Operations
1.Create two 3x3 matrices with random integer values between 1 and 10.
2.Perform element-wise addition, subtraction, and multiplication of the two matrices.
3.Compute the dot product of the two matrices.
4.Find the determinant of the first matrix.

In [7]:
import numpy as np
import random


In [8]:
m1=np.random.randint(1,11,size=(3,3))
print(m1)

m2=np.random.randint(1,11,size=(3,3))
print(m2)

[[10  6  6]
 [ 6  4  4]
 [ 7  7  1]]
[[ 6  5  1]
 [10 10  3]
 [ 6 10  5]]


In [9]:
# element wise addition
print("Addition of two matrices \n",m1+m2)
# element wise Subtraction
print("Subtraction of two matrices \n",m1-m2)
# element wise Multiplication
print("Multiplication of two matrices \n",m1*m2)

Addition of two matrices 
 [[16 11  7]
 [16 14  7]
 [13 17  6]]
Subtraction of two matrices 
 [[ 4  1  5]
 [-4 -6  1]
 [ 1 -3 -4]]
Multiplication of two matrices 
 [[60 30  6]
 [60 40 12]
 [42 70  5]]


In [10]:
# Dot Product of matrices
print(np.dot(m1,m2))

[[156 170  58]
 [100 110  38]
 [118 115  33]]


In [11]:
# finding the determinant
d1=np.linalg.det(m1)
d2=np.linalg.det(m2)
print(d1)
print(d2)

-23.999999999999982
2.2204460492503077e-14
