Problem 6: Advanced Indexing
1.Create a 5x5 matrix with values ranging from 0 to 24.
2.Select all elements from the matrix that are greater than 10.
3.Create a new matrix containing only the elements that are greater than 10.


In [1]:
import numpy as np


In [2]:
arr5=np.arange(0,25)
arr5.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [3]:
for i in arr5:
    if i > 10:
        print(i)

## or ##
greater_than_10 = arr5[arr5 > 10]
print("Elements greater than 10:")
print(greater_than_10)

11
12
13
14
15
16
17
18
19
20
21
22
23
24
Elements greater than 10:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [4]:
a=[]
for i in arr5:
    if i > 10:
        a.append(i)

a=np.array(a)
print(a)

## or ##
new_array = np.array(greater_than_10)
print("New array with elements greater than 10:")
print(new_array)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
New array with elements greater than 10:
[11 12 13 14 15 16 17 18 19 20 21 22 23 24]
