Problem 1: Basic Array Operations
1.Create a NumPy array of integers from 1 to 10.
2.Reshape the array to a 2x5 matrix.
3.Find the mean of the matrix.
4.Add 5 to each element in the matrix.
5.Multiply each element in the original array by 2 and store the result in a new array.

In [1]:
import numpy as np

In [2]:
arr1=np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
arr1=arr1.reshape(2,5)
print(arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [4]:
np.mean(arr1)

5.5

In [5]:
arr=arr1+5
print(arr)

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
new_arr1=arr1*2
print(new_arr1)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]
