Problem 2: Array Indexing and Slicing
1.Create a 4x4 matrix with values ranging from 1 to 16.
2.Extract the last row of the matrix.
3.Extract the first two columns of the matrix.
4.Replace the second row of the matrix with zeros.

In [1]:
import numpy as np

In [2]:
arr2=np.arange(1,17)
arr2=arr2.reshape(4,4)
print(arr2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [3]:
arr2[3:]

array([[13, 14, 15, 16]])

In [4]:
a=arr2[:,0:2]
print(a)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]


In [5]:
arr2[1:2]=[0,0,0,0]
print(arr2)

[[ 1  2  3  4]
 [ 0  0  0  0]
 [ 9 10 11 12]
 [13 14 15 16]]
