Problem:Make a matrix of 3X3, extract a submatrix from it. Specifically, consider the following tasks:
1.Extract a submatrix from a given 3x3 matrix by selecting rows 1 and 2, and columns 1 and 2.
2.Create a function that takes a matrix and the top-left and bottom-right coordinates of the submatrix and returns the submatrix.

In [1]:
import numpy as np

In [4]:
original_matrix=np.arange(1,10).reshape(3,3)
print(original_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
sub_matrix1=original_matrix[1:3,1:3]
print(sub_matrix1)


[[5 6]
 [8 9]]


In [14]:
def sub_matrix(matrix,top_left,bottom_right):
    row_start,column_start=top_left
    row_end,col_end=bottom_right
    return matrix[row_start:row_end,column_start:col_end]


result=sub_matrix(original_matrix,top_left=(1,1),bottom_right=(3,3))
print(result)

[[5 6]
 [8 9]]
