Problem 8: Linear Algebra
1.Create a 3x3 matrix with random values.
2.Compute the inverse of the matrix.
3.Verify the result by multiplying the matrix with its inverse (the result should be close to the identity matrix).

In [10]:
import numpy as np
import random

In [11]:
random_array=np.random.randint(1,11,9).reshape(3,3)
print(random_array)

[[2 2 4]
 [8 9 2]
 [8 8 6]]


In [12]:
inverse_random_array=np.linalg.inv(random_array)
print(inverse_random_array)

[[-1.9 -1.   1.6]
 [ 1.6  1.  -1.4]
 [ 0.4  0.  -0.1]]


In [17]:
a=np.dot(random_array,inverse_random_array)
a

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [-2.22044605e-16,  1.00000000e+00, -2.77555756e-16],
       [-2.22044605e-16,  0.00000000e+00,  1.00000000e+00]])

In [18]:
b=np.identity(3)
print(b)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
print(np.allclose(b, a))

True
