Problem 9: Array Manipulation
1.Create an array of 10 random integers between 1 and 50.
2.Sort the array in ascending order.
3.Find the unique elements in the array.
4.Find the index of the maximum value in the array.

In [1]:
import numpy as np
import random

In [2]:
arr=np.random.randint(1,51,10)
print(arr)

[ 1  6 50 18 50 50 29 45 44 22]


In [13]:
sorted_array=np.sort(arr)
print(sorted_array)

[ 1  6 18 22 29 44 45 50 50 50]


In [14]:
print(np.unique(arr))

[ 1  6 18 22 29 44 45 50]


In [17]:
print(np.max(arr))
print(np.argmax(arr))

50
7
