Problem 5: Logical Operations
1.Create an array of 20 random integers between 1 and 100.
2.Identify the elements that are greater than 50.
3.Replace all elements greater than 50 with 0.
4.Count the number of elements that are less than or equal to 50.


In [2]:
import numpy as np
import random

In [8]:
random_array=np.random.randint(1,101,20)
random_array

array([97, 46, 44, 44, 29, 98, 77, 17, 54,  3, 88, 35, 90, 27, 70, 68, 18,
        6,  9, 84])

In [9]:
for i in random_array:
    if i >50:
        print(i)

97
98
77
54
88
90
70
68
84


In [14]:
a=random_array.copy()
print(a)

a[a>50]=0
print(a)

[97 46 44 44 29 98 77 17 54  3 88 35 90 27 70 68 18  6  9 84]
[ 0 46 44 44 29  0  0 17  0  3  0 35  0 27  0  0 18  6  9  0]


In [7]:
for j in random_array:
    if j <=50:
        print(j)

36
39
3
42
14
18
38
19
35
15
35
34
