Problem 7: Broadcasting
1.Create a 3x3 matrix with values from 1 to 9.
2.Create a 1x3 vector with values [1, 0, 1].
3.Add the vector to each row of the matrix using broadcasting.

In [1]:
import numpy as np

In [14]:
arr=np.arange(1,10)
arr=arr.reshape(3,3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
arr1=np.array([1,0,1])
arr1

array([1, 0, 1])

In [17]:
new=arr+arr1
print(new)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]
